name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Start the server in the background
      - name: Start Server
        run: npm start &
      
      # Wait for the server to be ready
      - name: Wait for Server
        run: |
          until nc -z localhost 57134; do
            sleep 1
          done
      
      # Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          # No need to specify start and wait-on, as the server is already started and ready
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}